# ZooKeeper Deployment and Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  namespace: thomchat-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: wurstmeister/zookeeper:latest
        ports:
        - containerPort: 2181
        volumeMounts:
        - name: zookeeper-data
          mountPath: /opt/zookeeper-3.4.13/data
      volumes:
      - name: zookeeper-data
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
  namespace: thomchat-app
spec:
  selector:
    app: zookeeper
  ports:
  - port: 2181
    targetPort: 2181
