name: Deploy to AWS App Runner

on:
  push:
    branches:
      - main  
  workflow_dispatch:

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | \
          docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

      - name: Build & Push Frontend Image
        run: |
          FRONTEND_REPO=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/thomchat-frontend
          docker build \
          --build-arg REACT_APP_SOCKET_URL=${{ vars.REACT_APP_SOCKET_URL }} \
          -t thomchat-frontend ./frontend
          docker tag thomchat-frontend:latest $FRONTEND_REPO:latest
          docker push $FRONTEND_REPO:latest

      - name: Build & Push Backend Image
        run: |
          BACKEND_REPO=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/thomchat-backend
          docker build -t thomchat-backend ./backend
          docker tag thomchat-backend:latest $BACKEND_REPO:latest
          docker push $BACKEND_REPO:latest

      - name: Deploy Frontend to AWS App Runner
        run: |
          SERVICE_ARN=$(aws apprunner list-services --query "ServiceSummaryList[?ServiceName=='thomchat-frontend-service'].ServiceArn" --output text)

          IAM_ROLE_ARN="${{ secrets.IAM_ROLE_ARN }}"

          if [ -z "$SERVICE_ARN" ] || [ "$SERVICE_ARN" == "None" ]; then
            echo "Creating frontend-service..."
            aws apprunner create-service --service-name thomchat-frontend-service \
              --source-configuration '{
                "AuthenticationConfiguration": {
                  "AccessRoleArn": "'"$IAM_ROLE_ARN"'"
                },
                "ImageRepository": {
                  "ImageIdentifier": "${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/thomchat-frontend:latest",
                  "ImageRepositoryType": "ECR",
                  "ImageConfiguration": {
                    "Port": "3000",
                    "RuntimeEnvironmentVariables": {
                      "REACT_APP_SOCKET_URL": "${{ vars.REACT_APP_SOCKET_URL }}"
                    }
                  }
                },
                "AutoDeploymentsEnabled": true
              }'
          else
            echo "Updating frontend-service..."
            aws apprunner update-service --service-arn $SERVICE_ARN \
              --source-configuration '{
                "AuthenticationConfiguration": {
                  "AccessRoleArn": "'"$IAM_ROLE_ARN"'"
                },
                "ImageRepository": {
                  "ImageIdentifier": "${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/thomchat-frontend:latest",
                  "ImageRepositoryType": "ECR",
                  "ImageConfiguration": {
                    "Port": "3000",
                    "RuntimeEnvironmentVariables": {
                      "REACT_APP_SOCKET_URL": "${{ vars.REACT_APP_SOCKET_URL }}"
                    }
                  }
                },
                "AutoDeploymentsEnabled": true
              }'
          fi

      - name: Deploy Backend to AWS App Runner
        run: |
          SERVICE_ARN=$(aws apprunner list-services --query "ServiceSummaryList[?ServiceName=='thomchat-backend-service'].ServiceArn" --output text)

          IAM_ROLE_ARN="${{ secrets.IAM_ROLE_ARN }}"

          if [ -z "$SERVICE_ARN" ] || [ "$SERVICE_ARN" == "None" ]; then
            echo "Creating backend-service..."
            aws apprunner create-service --service-name thomchat-backend-service \
              --source-configuration '{
                "AuthenticationConfiguration": {
                  "AccessRoleArn": "'"$IAM_ROLE_ARN"'"
                },
                "ImageRepository": {
                  "ImageIdentifier": "${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/thomchat-backend:latest",
                  "ImageRepositoryType": "ECR",
                  "ImageConfiguration": {
                    "Port": "8000"
                  }
                },
                "AutoDeploymentsEnabled": true
              }'
          else
            echo "Updating backend-service..."
            aws apprunner update-service --service-arn $SERVICE_ARN \
              --source-configuration '{
                "AuthenticationConfiguration": {
                  "AccessRoleArn": "'"$IAM_ROLE_ARN"'"
                },
                "ImageRepository": {
                  "ImageIdentifier": "${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/thomchat-backend:latest",
                  "ImageRepositoryType": "ECR",
                  "ImageConfiguration": {
                    "Port": "8000"
                  }
                },
                "AutoDeploymentsEnabled": true
              }'
          fi